package main

const (
	AENC = "AENC" //Audio encryption
	APIC = "APIC" //Attached picture
	ASPI = "ASPI" //Audio seek point index
	COMM = "COMM" //Comments
	COMR = "COMR" //Commercial frame
	ENCR = "ENCR" //Encryption method registration
	EQU2 = "EQU2" //Equalisation (2)
	ETCO = "ETCO" //Event timing codes
	GEOB = "GEOB" //General encapsulated object
	GRID = "GRID" //Group identification registration
	LINK = "LINK" //Linked information
	MCDI = "MCDI" //Music CD identifier
	MLLT = "MLLT" //MPEG location lookup table
	OWNE = "OWNE" //Ownership frame
	PRIV = "PRIV" //Private frame
	PCNT = "PCNT" //Play counter
	POPM = "POPM" //Popularimeter
	POSS = "POSS" //Position synchronisation frame
	RBUF = "RBUF" //Recommended buffer size
	RVA2 = "RVA2" //Relative volume adjustment (2)
	RVRB = "RVRB" //Reverb
	SEEK = "SEEK" //Seek frame
	SIGN = "SIGN" //Signature frame
	SYLT = "SYLT" //Synchronised lyric/text
	SYTC = "SYTC" //Synchronised tempo codes
	TALB = "TALB" //Album/Movie/Show title
	TBPM = "TBPM" //BPM (beats per minute)
	TCOM = "TCOM" //Composer
	TCON = "TCON" //Content type
	TCOP = "TCOP" //Copyright message
	TDEN = "TDEN" //Encoding time
	TDLY = "TDLY" //Playlist delay
	TDOR = "TDOR" //Original release time
	TDRC = "TDRC" //Recording time
	TDRL = "TDRL" //Release time
	TDTG = "TDTG" //Tagging time
	TENC = "TENC" //Encoded by
	TEXT = "TEXT" //Lyricist/Text writer
	TFLT = "TFLT" //File type
	TIPL = "TIPL" //Involved people list
	TIT1 = "TIT1" //Content group description
	TIT2 = "TIT2" //Title/songname/content description
	TIT3 = "TIT3" //Subtitle/Description refinement
	TKEY = "TKEY" //Initial key
	TLAN = "TLAN" //Language(s)
	TLEN = "TLEN" //Length
	TMCL = "TMCL" //Musician credits list
	TMED = "TMED" //Media type
	TMOO = "TMOO" //Mood
	TOAL = "TOAL" //Original album/movie/show title
	TOFN = "TOFN" //Original filename
	TOLY = "TOLY" //Original lyricist(s)/text writer(s)
	TOPE = "TOPE" //Original artist(s)/performer(s)
	TOWN = "TOWN" //File owner/licensee
	TPE1 = "TPE1" //Lead performer(s)/Soloist(s)
	TPE2 = "TPE2" //Band/orchestra/accompaniment
	TPE3 = "TPE3" //Conductor/performer refinement
	TPE4 = "TPE4" //Interpreted, remixed, or otherwise modified by
	TPOS = "TPOS" //Part of a set
	TPRO = "TPRO" //Produced notice
	TPUB = "TPUB" //Publisher
	TRCK = "TRCK" //Track number/Position in set
	TRSN = "TRSN" //Internet radio station name
	TRSO = "TRSO" //Internet radio station owner
	TSOA = "TSOA" //Album sort order
	TSOP = "TSOP" //Performer sort order
	TSOT = "TSOT" //Title sort order
	TSRC = "TSRC" //ISRC (international standard recording code)
	TSSE = "TSSE" //Software/Hardware and settings used for encoding
	TSST = "TSST" //Set subtitle
	TXXX = "TXXX" //User defined text information frame
	UFID = "UFID" //Unique file identifier
	USER = "USER" //Terms of use
	USLT = "USLT" //Unsynchronised lyric/text transcription
	WCOM = "WCOM" //Commercial information
	WCOP = "WCOP" //Copyright/Legal information
	WOAF = "WOAF" //Official audio file webpage
	WOAR = "WOAR" //Official artist/performer webpage
	WOAS = "WOAS" //Official audio source webpage
	WORS = "WORS" //Official Internet radio station homepage
	WPAY = "WPAY" //Payment
	WPUB = "WPUB" //Publishers official webpage
	WXXX = "WXXX" //User defined URL link frame
)
